/* worldspace/worldspace.js — the runtime of the public observatory of compatible worlds.
 *
 * The page carries its numbers in #ws-data, generated by scripts/generate_worldspace.py
 * from the claim registry. This file computes no probability: it counts rings on
 * discs, indexes the registered world for that count, and draws. It stores nothing,
 * sends nothing, and draws no random number. If any reachable state would show a
 * world the registry does not license, the instrument halts and says so.
 *
 * Acts: predict → touch → field (→ assume) → exit. Every transition is an explicit
 * state change under prefers-reduced-motion; the animated path carries no
 * information the reduced path lacks. */
(function () {
  'use strict';
  var dataEl = document.getElementById('ws-data');
  if (!dataEl) return;
  var D = JSON.parse(dataEl.textContent);
  var S_ = D.strings;
  var root = document.documentElement;
  var reduced = matchMedia('(prefers-reduced-motion: reduce)');
  var $ = function (id) { return document.getElementById(id); };
  var stage = $('ws'), live = $('ws-live'), ledger = $('ws-ledger');
  var N = D.n, SIDE = D.side, A = D.arrangement.a, HOME = D.arrangement.b, QMAX = Math.min(D.missA, D.missB);
  var aSet = {}; A.forEach(function (c) { aSet[c] = true; });

  /* ---- state ------------------------------------------------------ */
  var S = { act: 'predict', prediction: null, q: 0, visited: {}, assume: false, sound: false,
            rings: HOME.slice(), settled: false, indep: false, opened: false, halted: false };
  S.visited[0] = true;

  function halt(reason) {
    S.halted = true;
    var p = document.createElement('p'); p.className = 'ws-halt';
    p.textContent = 'INSTRUMENT HALTED · ' + reason + ' · the static proof below still stands';
    stage.appendChild(p);
    root.classList.remove('ws-js');
    throw new Error('worldspace halted: ' + reason);
  }
  function check() {
    var seen = {}, q = 0;
    if (S.rings.length !== D.missB) halt('ring count is not ' + D.missB);
    S.rings.forEach(function (c) {
      if (!(c >= 0 && c < N)) halt('ring outside the population');
      if (seen[c]) halt('two rings on one item');
      seen[c] = true; if (aSet[c]) q++;
    });
    if (A.length !== D.missA) halt('disc count is not ' + D.missA);
    if (q < 0 || q > QMAX) halt('joint count ' + q + ' outside 0…' + QMAX);
    if (!D.worlds[q] || D.worlds[q].q !== q) halt('no registered world for count ' + q);
    return q;
  }
  function validateSpecimens() {
    D.specimens.columns.forEach(function (col, q) {
      col.forEach(function (sp) {
        var a = {}, both = 0;
        if (sp.a.length !== D.missA || sp.b.length !== D.missB) halt('a specimen does not carry the declared scores');
        sp.a.forEach(function (c) { a[c] = true; });
        sp.b.forEach(function (c) { if (a[c]) both++; });
        if (both !== q) halt('a specimen sits in the wrong column');
      });
    });
  }

  /* ---- readouts and announcements ---------------------------------- */
  var roA = document.querySelector('[data-readout="a"]'), roB = document.querySelector('[data-readout="b"]'),
      roBoth = document.querySelector('[data-readout="both"]'), stamp = $('ws-stamp'), inv = $('ws-invariant');
  var changedOnce = false;
  function setLedger(key) { ledger.textContent = D.ledger[key]; }
  function announce(msg) { live.textContent = ''; setTimeout(function () { live.textContent = msg; }, 30); }
  function renderReadouts(prevQ) {
    var q = S.q;
    roA.textContent = String(D.missA); roB.textContent = String(D.missB);
    if (roA.textContent !== String(D.missA) || roB.textContent !== String(D.missB)) halt('a score readout moved');
    roBoth.textContent = String(q);
    stage.setAttribute('data-both', String(q));
    stage.setAttribute('data-a', roA.textContent); stage.setAttribute('data-b', roB.textContent);
    var w = D.worlds[q];
    if (w.witness) { stamp.hidden = false; stamp.textContent = w.witness === 'lower' ? S_.witness_lower : S_.witness_upper; }
    else stamp.hidden = true;
    if (prevQ !== undefined && prevQ !== q) {
      if (!changedOnce) {
        changedOnce = true; inv.hidden = false;
        document.querySelectorAll('[data-fixed]').forEach(function (el) { el.hidden = false; });
      }
      announce('Both miss ' + q + ' of ' + N + '. Guard A still misses ' + D.missA + ' of ' + N + '; guard B still misses ' + D.missB + ' of ' + N + '.');
    }
    [$('ws-range'), $('ws-range2')].forEach(function (r) { if (r) { r.value = String(q); r.setAttribute('aria-valuetext', q + ' of ' + N + ' both miss'); } });
  }

  /* ---- the sheet ---------------------------------------------------- */
  var sheet = $('ws-sheet'), ringEls = [];
  function cellXY(c) { return [c % SIDE, Math.floor(c / SIDE)]; }
  function placeEl(el, c) { var xy = cellXY(c); el.style.transform = 'translate(' + (xy[0] * 100) + '%,' + (xy[1] * 100) + '%)'; }
  function buildSheet(container, aCells, ringCells, interactive) {
    container.innerHTML = '';
    aCells.forEach(function (c) { var d = document.createElement('span'); d.className = 'ws-disc'; placeEl(d, c); container.appendChild(d); });
    var els = [];
    ringCells.forEach(function (c, i) {
      var b = document.createElement(interactive ? 'button' : 'span');
      b.className = 'ws-ring' + (aCells.indexOf(c) >= 0 ? ' on' : '');
      if (interactive) { b.type = 'button'; b.setAttribute('data-ring', String(i)); }
      placeEl(b, c); container.appendChild(b); els.push(b);
    });
    return els;
  }
  function ringLabel(i) {
    var c = S.rings[i], on = !!aSet[c];
    return 'Ring ' + (i + 1) + ' of ' + D.missB + ', item ' + (c + 1) + ': ' + (on ? 'both guards miss this item. Activate to move it off the disc.' : 'only guard B misses this item. Activate to move it onto a disc.');
  }
  function refreshRings() {
    ringEls.forEach(function (el, i) {
      var c = S.rings[i];
      el.classList.toggle('on', !!aSet[c]);
      el.setAttribute('aria-label', ringLabel(i));
      if (!el.classList.contains('dragging')) placeEl(el, c);
    });
  }
  function occupied(c) { return S.rings.indexOf(c) >= 0; }
  function moveRing(i, c) {
    if (c < 0 || c >= N) return false;
    if (S.rings[i] === c) return false;
    if (occupied(c)) return false;
    var prev = S.q;
    S.rings[i] = c;
    S.q = check();
    S.visited[S.q] = true;
    refreshRings(); renderReadouts(prev);
    if (S.q !== prev) tone(S.q);
    afterMove();
    return true;
  }
  function freeDisc() { for (var k = 0; k < A.length; k++) if (!occupied(A[k])) return A[k]; return -1; }
  function freeHome(i) {
    if (!occupied(HOME[i])) return HOME[i];
    for (var k = 0; k < HOME.length; k++) if (!occupied(HOME[k])) return HOME[k];
    for (var c = 0; c < N; c++) if (!aSet[c] && !occupied(c)) return c;
    return -1;
  }
  function hop(i) { var c = S.rings[i]; moveRing(i, aSet[c] ? freeHome(i) : freeDisc()); }
  /* the canonical placement for a count: ring i on disc i for i < q, at home otherwise */
  function setBoth(q) {
    q = Math.max(0, Math.min(QMAX, Math.round(Number(q) || 0)));
    var prev = S.q, target = [];
    for (var i = 0; i < D.missB; i++) target.push(i < q ? A[i] : HOME[i]);
    S.rings = target;
    S.q = check();
    S.visited[S.q] = true;
    refreshRings(); renderReadouts(prev);
    if (S.q !== prev) tone(S.q);
    afterMove();
  }
  /* a control the visitor caused to appear is brought into view; under reduced motion the scroll is a cut */
  function reveal(el) { try { el.scrollIntoView({ block: 'nearest', behavior: reduced.matches ? 'auto' : 'smooth' }); } catch (e) { /* older engines */ } }
  function afterMove() {
    var distinct = Object.keys(S.visited).length;
    if (S.act === 'touch' && distinct >= 2 && $('ws-open-row').hidden) {
      $('ws-name').hidden = false; $('ws-open-row').hidden = false;
      reveal($('ws-open-row'));
    }
    if (S.act === 'field') { drawField(); placeMarks(); updateAssumeText(); }
  }

  /* ---- drag (pointer events; tap or Enter hops) ---------------------- */
  var drag = null;
  function cellAt(clientX, clientY) {
    var r = sheet.getBoundingClientRect();
    var x = Math.floor((clientX - r.left) / r.width * SIDE), y = Math.floor((clientY - r.top) / r.height * SIDE);
    if (x < 0 || y < 0 || x >= SIDE || y >= SIDE) return -1;
    return y * SIDE + x;
  }
  sheet.addEventListener('pointerdown', function (e) {
    var el = e.target.closest('.ws-ring'); if (!el || e.button) return;
    var i = Number(el.getAttribute('data-ring'));
    drag = { i: i, el: el, x0: e.clientX, y0: e.clientY, moved: false, id: e.pointerId };
    el.setPointerCapture(e.pointerId);
  });
  sheet.addEventListener('pointermove', function (e) {
    if (!drag || e.pointerId !== drag.id) return;
    var dx = e.clientX - drag.x0, dy = e.clientY - drag.y0;
    if (!drag.moved && Math.hypot(dx, dy) < 4) return;
    drag.moved = true; drag.el.classList.add('dragging');
    var xy = cellXY(S.rings[drag.i]), r = sheet.getBoundingClientRect(), cell = r.width / SIDE;
    drag.el.style.transform = 'translate(' + (xy[0] * 100 + dx / cell * 100) + '%,' + (xy[1] * 100 + dy / cell * 100) + '%)';
  });
  function endDrag(e) {
    if (!drag || e.pointerId !== drag.id) return;
    var d = drag; drag = null;
    d.el.classList.remove('dragging');
    if (d.moved) { var c = cellAt(e.clientX, e.clientY); if (!moveRing(d.i, c)) placeEl(d.el, S.rings[d.i]); }
    else hop(d.i);
  }
  sheet.addEventListener('pointerup', endDrag);
  sheet.addEventListener('pointercancel', function (e) { if (drag && e.pointerId === drag.id) { drag.el.classList.remove('dragging'); placeEl(drag.el, S.rings[drag.i]); drag = null; } });
  sheet.addEventListener('keydown', function (e) {
    var el = e.target.closest('.ws-ring'); if (!el) return;
    if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); hop(Number(el.getAttribute('data-ring'))); }
  });
  sheet.addEventListener('click', function (e) { /* pointer events already handled activation; keep keyboard-generated clicks from double-firing */
    if (e.detail === 0) { var el = e.target.closest('.ws-ring'); if (el && !e.defaultPrevented) { /* synthesized by Enter/Space: handled in keydown */ } }
  });

  /* ---- acts ---------------------------------------------------------- */
  function setAct(id) {
    ['predict', 'touch', 'field'].forEach(function (a) { $('act-' + a).hidden = a !== id; });
    S.act = id; stage.setAttribute('data-act', id); setLedger(id);
  }
  function commit(n) {
    S.prediction = (n === null || n === undefined || n === '' || isNaN(n)) ? null : Math.max(0, Math.min(N, Math.round(Number(n))));
    $('ro-both').hidden = false;
    setAct('touch');
    renderReadouts();
    var first = ringEls[0]; if (first) first.focus({ preventScroll: true });
    announce('Touch the world. ' + D.missA + ' discs are items guard A misses; ' + D.missB + ' rings are items guard B misses. Both miss ' + S.q + '.');
  }
  $('ws-predict').addEventListener('submit', function (e) {
    e.preventDefault();
    var v = $('ws-guess').value.trim();
    if (v === '' || !/^\d+$/.test(v) || Number(v) > N) { $('ws-guess').focus(); announce('Enter a whole number from 0 to ' + N + ', or enter without a guess.'); return; }
    commit(Number(v));
  });
  $('ws-noguess').addEventListener('click', function () { commit(null); });
  $('ws-skip').addEventListener('click', function () { $('exit').classList.remove('ws-staged'); });
  $('ws-minus').addEventListener('click', function () { setBoth(S.q - 1); });
  $('ws-plus').addEventListener('click', function () { setBoth(S.q + 1); });
  $('ws-range').addEventListener('input', function () { setBoth($('ws-range').value); });
  $('ws-minus2').addEventListener('click', function () { setBoth(S.q - 1); });
  $('ws-plus2').addEventListener('click', function () { setBoth(S.q + 1); });
  $('ws-range2').addEventListener('input', function () { setBoth($('ws-range2').value); });

  /* ---- the field ----------------------------------------------------- */
  var canvas = $('ws-canvas'), ctx = canvas.getContext('2d'), wrap = $('ws-fieldwrap');
  var G = null;        // geometry: W, H, dpr, x0, x1, tile s, gap, rows, cols, perColumn
  var anim = null;     // pull-back animation state
  function geometry() {
    var W = wrap.clientWidth || 320, phone = W < 560;
    var segW = W * (phone ? 0.88 : 0.84), colW = segW / (QMAX + 1);
    var gap = phone ? 5 : 6;
    var cols = (!phone && colW >= 2 * 24 + 3 * gap) ? 2 : 1;
    var s = Math.floor(Math.min(phone ? 30 : 36, (colW - (cols + 1) * gap) / cols));
    var per = cols === 2 ? D.specimens.perColumn : D.specimens.phonePerColumn;
    if (S.posterRows) per = Math.min(per, cols * (S.posterRows - 1));
    var rows = 1 + Math.ceil(per / cols);
    var top = 6, H = top + rows * (s + gap) + gap;
    var x0 = colW / 2, x1 = segW - colW / 2;
    return { W: W, H: H, dpr: Math.min(2, devicePixelRatio || 1), x0: x0, x1: x1, s: s, gap: gap, rows: rows, cols: cols, per: per, colW: colW, top: top };
  }
  function colX(q) { return G.x0 + (G.x1 - G.x0) * q / QMAX; }
  function tileRect(q, k) {  // k = 0 is the visitor's slot at the top of its column; specimens follow
    var col = k % G.cols, row = Math.floor(k / G.cols);
    var totalW = G.cols * G.s + (G.cols - 1) * G.gap;
    var x = colX(q) - totalW / 2 + col * (G.s + G.gap), y = G.top + G.gap + row * (G.s + G.gap);
    return { x: x, y: y, s: G.s };
  }
  function drawTile(x, y, s, a, b, opts) {
    var alpha = opts && opts.alpha != null ? opts.alpha : 1, cell = s / SIDE;
    ctx.save(); ctx.globalAlpha = alpha;
    ctx.fillStyle = '#EDE8DA'; ctx.fillRect(x, y, s, s);
    var amap = {}; a.forEach(function (c) { amap[c] = true; });
    var bmap = {}; b.forEach(function (c) { bmap[c] = true; });
    for (var c = 0; c < N; c++) {
      var cx = x + (c % SIDE) * cell + cell / 2, cy = y + Math.floor(c / SIDE) * cell + cell / 2;
      if (amap[c] && bmap[c]) { ctx.fillStyle = '#14170F'; ctx.beginPath(); ctx.arc(cx, cy, cell * 0.46, 0, 6.2832); ctx.fill(); }
      else if (amap[c]) { ctx.fillStyle = '#14170F'; ctx.beginPath(); ctx.arc(cx, cy, cell * 0.26, 0, 6.2832); ctx.fill(); }
      else if (bmap[c]) { ctx.strokeStyle = '#14170F'; ctx.lineWidth = Math.max(0.8, cell * 0.14); ctx.beginPath(); ctx.arc(cx, cy, cell * 0.34, 0, 6.2832); ctx.stroke(); }
    }
    if (opts && opts.gold) { ctx.strokeStyle = '#C9A15E'; ctx.lineWidth = 2; ctx.strokeRect(x - 2, y - 2, s + 4, s + 4); }
    ctx.restore();
  }
  function columnAlpha(q) { return S.assume ? (q === D.independenceQ ? 1 : 0.1) : 1; }
  function drawField(progress) {
    if (!G) G = geometry();
    var p = progress == null ? 1 : progress;
    canvas.width = Math.round(G.W * G.dpr); canvas.height = Math.round(G.H * G.dpr);
    canvas.style.height = G.H + 'px';
    ctx.setTransform(G.dpr, 0, 0, G.dpr, 0, 0);
    ctx.fillStyle = '#0B0F0A'; ctx.fillRect(0, 0, G.W, G.H);
    // specimens fade in with the pull-back
    for (var q = 0; q <= QMAX; q++) {
      var col = D.specimens.columns[q];
      for (var k = 0; k < G.per && k < col.length; k++) {
        var t = tileRect(q, k + 1);
        drawTile(t.x, t.y, t.s, col[k].a, col[k].b, { alpha: p * columnAlpha(q) });
      }
    }
    // the visitor's world: from a large central sheet to its slot
    var slot = tileRect(S.q, 0), big = Math.min(G.W * 0.5, G.H * 0.9, 220);
    var e = 1 - Math.pow(1 - p, 3);
    var x = (G.W / 2 - big / 2) + (slot.x - (G.W / 2 - big / 2)) * e, y = (G.H / 2 - big / 2) + (slot.y - (G.H / 2 - big / 2)) * e, s = big + (slot.s - big) * e;
    var excluded = S.assume && S.q !== D.independenceQ;
    drawTile(x, y, s, A, S.rings, { gold: true, alpha: excluded ? 0.35 : 1 });
  }
  function mark(el, x, show) {
    el.hidden = !show;
    if (!show) return;
    var pt = el.querySelector('.pt'), txt = el.querySelector('.txt');
    pt.style.left = x + 'px';
    txt.style.left = x + 'px';
    txt.style.transform = 'translateX(-50%)';
    var w = txt.getBoundingClientRect().width, pad = 2;
    if (x - w / 2 < pad) txt.style.transform = 'translateX(' + (-x + pad) + 'px)';
    else if (x + w / 2 > G.W - pad) txt.style.transform = 'translateX(' + (-w + (G.W - pad - x)) + 'px)';
  }
  function placeMarks() {
    if (!G) G = geometry();
    var seg = $('ws-seg'), tail = $('ws-tail');
    var onePt = S.assume;
    seg.style.left = (onePt ? colX(D.independenceQ) - 3 : colX(0)) + 'px';
    seg.style.width = (onePt ? 6 : colX(QMAX) - colX(0)) + 'px';
    tail.style.left = colX(QMAX) + 'px'; tail.style.width = (G.W - colX(QMAX)) + 'px';
    var axis = $('ws-axis');
    axis.querySelectorAll('.tick').forEach(function (t) { t.remove(); });
    for (var q = 0; q <= QMAX; q++) {
      var t = document.createElement('span'); t.className = 'tick' + (q === 0 || q === QMAX ? ' end' : ''); t.textContent = String(q); t.style.left = colX(q) + 'px'; axis.appendChild(t);
    }
    mark($('ws-mark-world'), colX(S.q), true);
    if (S.prediction == null) mark($('ws-mark-pred'), 0, false);
    else {
      var n = S.prediction, x = n <= QMAX ? colX(n) : colX(QMAX) + (G.W - 6 - colX(QMAX)) * (n - QMAX) / (N - QMAX);
      $('ws-pred-txt').textContent = n > QMAX ? S_.predicted_outside.replace('{n}', n)
        : (S.indep && n === D.independenceQ ? S_.predicted_independence.replace('{n}', n) : S_.predicted.replace('{n}', n));
      mark($('ws-mark-pred'), x, true);
    }
    mark($('ws-mark-ind'), colX(D.independenceQ), S.indep);
  }
  function openField() {
    if (S.opened) return;
    S.opened = true; S.settled = false;
    setAct('field'); $('ro-both').hidden = false;
    G = geometry();
    var mw = $('ws-mark-world'); mw.hidden = true;
    lowTone();
    var finish = function () {
      drawField(1); placeMarks(); S.settled = true;
      $('field-h').hidden = false;
      setTimeout(landIndependence, reduced.matches ? 0 : 900);
    };
    if (reduced.matches) { finish(); return; }
    var t0 = null;
    anim = function (ts) {
      if (t0 === null) t0 = ts;
      var p = Math.min(1, (ts - t0) / 900);
      drawField(p);
      if (p < 1) requestAnimationFrame(anim); else { anim = null; finish(); }
    };
    requestAnimationFrame(anim);
  }
  function landIndependence() {
    if (S.indep) return;
    S.indep = true;
    $('ws-indep').hidden = false; $('ws-continue-row').hidden = false;
    placeMarks(); highTone(); setLedger('assume');
    reveal($('ws-indep'));
    announce('Independence: ten percent times ten percent is one percent. One assumption, one point on the axis.');
  }
  function updateAssumeText() {
    var t = $('ws-assume-text');
    if (!S.assume) { t.hidden = true; return; }
    t.hidden = false;
    t.textContent = S_.assume_on + (S.q !== D.independenceQ ? ' ' + S_.your_world + ': ' + S_.excluded + '.' : '');
  }
  $('ws-open').addEventListener('click', openField);
  $('ws-assume').addEventListener('click', function () {
    S.assume = !S.assume;
    $('ws-assume').setAttribute('aria-checked', String(S.assume));
    $('ws-axis').classList.toggle('collapsed', S.assume);
    drawField(); placeMarks(); updateAssumeText(); glide(S.assume ? -1 : 1);
    announce(S.assume ? S_.assume_on : 'The assumption is released. Every position is open again.');
  });
  $('ws-continue').addEventListener('click', function () {
    $('exit').classList.remove('ws-staged'); setLedger('exit');
    $('exit').scrollIntoView({ behavior: reduced.matches ? 'auto' : 'smooth', block: 'start' });
    setTimeout(function () { $('exit-h').setAttribute('tabindex', '-1'); $('exit-h').focus({ preventScroll: true }); }, reduced.matches ? 0 : 500);
  });
  function inspect(q, k) {
    var sp = D.specimens.columns[q][k]; if (!sp) return;
    $('ws-inspector').hidden = false;
    buildSheet($('ws-spec-sheet'), sp.a, sp.b, false);
    $('ws-spec-cap').textContent = S_.specimen_caption.replace('{q}', q);
    $('ws-back').focus({ preventScroll: true });
  }
  $('ws-inspect').addEventListener('click', function () { inspect(S.q, 0); });
  $('ws-back').addEventListener('click', function () { $('ws-inspector').hidden = true; $('ws-inspect').focus({ preventScroll: true }); });
  canvas.addEventListener('click', function (e) {
    if (!S.settled || !G) return;
    var r = canvas.getBoundingClientRect(), x = e.clientX - r.left, y = e.clientY - r.top;
    for (var q = 0; q <= QMAX; q++) for (var k = 0; k < G.per; k++) {
      var t = tileRect(q, k + 1);
      if (x >= t.x && x <= t.x + t.s && y >= t.y && y <= t.y + t.s) { inspect(q, k); return; }
    }
  });
  addEventListener('resize', function () { if (S.act === 'field' && S.settled) { G = geometry(); drawField(); placeMarks(); } });

  /* ---- sound: opt-in, procedural, pitch encodes the joint count ----------- */
  var AC = null;
  function ac() { if (!AC) { var C = window.AudioContext || window.webkitAudioContext; if (!C) return null; AC = new C(); } if (AC.state === 'suspended') AC.resume(); return AC; }
  function beep(freq, dur, gain, type, glideTo) {
    if (!S.sound) return; var c = ac(); if (!c) return;
    var o = c.createOscillator(), g = c.createGain(), t = c.currentTime;
    o.type = type || 'sine'; o.frequency.setValueAtTime(freq, t);
    if (glideTo) o.frequency.exponentialRampToValueAtTime(glideTo, t + dur);
    g.gain.setValueAtTime(0.0001, t); g.gain.exponentialRampToValueAtTime(gain || 0.08, t + 0.012); g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    o.connect(g); g.connect(c.destination); o.start(t); o.stop(t + dur + 0.02);
  }
  function tone(q) { beep(330 * Math.pow(2, q / 12), 0.09, 0.07); }
  function lowTone() { beep(110, 0.9, 0.05); }
  function highTone() { beep(660, 0.14, 0.06); }
  function glide(dir) { beep(dir < 0 ? 330 : 110, 0.3, 0.05, 'sine', dir < 0 ? 110 : 330); }
  var soundBtn = $('ws-sound');
  soundBtn.hidden = !(window.AudioContext || window.webkitAudioContext);
  soundBtn.addEventListener('click', function () {
    S.sound = !S.sound; soundBtn.setAttribute('aria-pressed', String(S.sound)); soundBtn.textContent = S.sound ? S_.sound_on : S_.sound_off;
    if (S.sound) { ac(); tone(S.q); }
  });

  /* ---- init ---------------------------------------------------------- */
  validateSpecimens();
  S.q = check();
  ringEls = buildSheet(sheet, A, S.rings, true);
  refreshRings(); renderReadouts();
  $('exit').classList.add('ws-staged');
  root.classList.add('ws-js');
  setLedger('predict');
  if (location.hash === '#exit') $('exit').classList.remove('ws-staged');

  /* a small read-only surface for the QA harness; it drives the page through real input events */
  window.__ws = {
    poster: function () { S.posterRows = 4; stage.classList.add('ws-poster'); if (S.act === 'field') { G = geometry(); drawField(); placeMarks(); } },
    state: function () { return { act: S.act, q: S.q, prediction: S.prediction, assume: S.assume, indep: S.indep, settled: S.settled, sound: S.sound, halted: S.halted, visited: Object.keys(S.visited).map(Number).sort(function (a, b) { return a - b; }), a: A.slice(), rings: S.rings.slice(), reduced: reduced.matches }; },
    setBoth: setBoth
  };
})();
