/* trials/necromancer/trial.js — the runtime of Trial IV.
 *
 * The page carries its cases, strings, templates and the seeded arm table in
 * #tr-data, generated by scripts/generate_trial.py. This file renders phases,
 * records what the learner does, and builds the receipt. It stores nothing,
 * sends nothing, and draws no random number: the arm is looked up from the
 * embedded table, and the seal hash is the digest of what the learner sealed.
 *
 * Arm A: enrol → pre → claim → seal → evidence → sort → debrief → update → cold → receipt
 * Arm B: enrol → pre → claim → evidence → seal → sort → debrief → update → cold → receipt */
(function () {
  'use strict';
  var dataEl = document.getElementById('tr-data');
  if (!dataEl) return;
  var D = JSON.parse(dataEl.textContent);
  var S_ = D.strings;
  var root = document.documentElement;
  root.classList.add('tr-js');
  var $ = function (id) { return document.getElementById(id); };
  var main = $('main'), live = $('tr-live');
  var ORDER = { A: ['enrol', 'pre', 'claim', 'seal', 'evidence', 'sort', 'debrief', 'update', 'cold', 'receipt'],
                B: ['enrol', 'pre', 'claim', 'evidence', 'seal', 'sort', 'debrief', 'update', 'cold', 'receipt'] };
  var S = { slot: null, arm: null, phase: 'enrol', t0: null, phases: [], handle: '', prediction: null,
            seal: null, sorts: { pre: {}, trained: {}, cold: {} }, updated: '', recall: '', confidence: null, helped: null, comment: '' };

  function fmt(s, vars) { return s.replace(/\{(\w+)\}/g, function (_, k) { return vars[k] !== undefined ? String(vars[k]) : '{' + k + '}'; }); }
  function el(tag, cls, text) { var e = document.createElement(tag); if (cls) e.className = cls; if (text !== undefined) e.textContent = text; return e; }
  function announce(msg) { live.textContent = ''; setTimeout(function () { live.textContent = msg; }, 30); }
  function now() { return Date.now(); }
  function pad(n) { return (n < 10 ? '0' : '') + n; }

  /* ---- clock ------------------------------------------------------ */
  function tick() {
    if (S.t0 === null) return;
    var s = Math.floor((now() - S.t0) / 1000);
    $('tr-elapsed').textContent = pad(Math.floor(s / 60)) + ':' + pad(s % 60);
  }
  setInterval(tick, 1000);

  /* ---- phases ----------------------------------------------------- */
  function order() { if (!ORDER[S.arm]) throw new Error('trial: unknown arm ' + S.arm); return ORDER[S.arm]; }
  function go(pid) {
    var t = now();
    if (S.phases.length) S.phases[S.phases.length - 1].ended = t;
    S.phases.push({ id: pid, started: t, ended: null });
    S.phase = pid;
    main.setAttribute('data-phase', pid);
    order().forEach(function (p) { $('phase-' + p).hidden = p !== pid; });
    var h = $('ph-' + pid + '-h');
    if (h) { h.focus({ preventScroll: true }); h.scrollIntoView({ block: 'start' }); }
    announce(h ? h.textContent : pid);
  }
  function next() { var o = order(), i = o.indexOf(S.phase); if (i >= 0 && i + 1 < o.length) go(o[i + 1]); }

  /* ---- case rendering --------------------------------------------- */
  function renderCase(container, c, opts) {
    container.innerHTML = '';
    container.appendChild(el('span', 'mono tr-lbl', S_.case_setting));
    (Array.isArray(c.setting) ? c.setting : [c.setting]).forEach(function (s) { container.appendChild(el('p', null, s)); });
    container.appendChild(el('span', 'mono tr-lbl', S_.case_claim));
    container.appendChild(el('p', 'tr-claim', c.claim));
    if (opts.commitment) {
      container.appendChild(el('span', 'mono tr-lbl', opts.caseId === 'trained' ? S_.case_commitment : S_.case_commitment_bare));
      var box = el('div', 'tr-commit'), dl = el('dl');
      dl.appendChild(el('dt', null, S_.case_falsifier)); dl.appendChild(el('dd', null, opts.commitment.falsifier));
      dl.appendChild(el('dt', null, S_.case_consequence)); dl.appendChild(el('dd', null, opts.commitment.consequence));
      dl.appendChild(el('dt', null, S_.case_forbidden));
      var dd = el('dd'), ul = el('ul');
      opts.commitment.forbidden.forEach(function (f) { ul.appendChild(el('li', null, f)); });
      dd.appendChild(ul); dl.appendChild(dd); box.appendChild(dl); container.appendChild(box);
    }
    if (opts.evidence) {
      container.appendChild(el('span', 'mono tr-lbl', S_.case_evidence));
      var ev = el('ul', 'tr-evidence');
      c.evidence.forEach(function (e) { ev.appendChild(el('li', null, e)); });
      container.appendChild(ev);
    }
    if (opts.moves) renderSort(container, c, opts.caseId, opts.onSubmit);
  }
  function renderSort(container, c, caseId, onSubmit) {
    container.appendChild(el('span', 'mono tr-lbl', S_.case_moves));
    var form = el('form'); form.noValidate = true; form.id = 'sort-' + caseId;
    var list = el('ol', 'tr-moves');
    c.moves.forEach(function (mv) {
      var li = el('li', 'tr-move'), fs = el('fieldset'), lg = el('legend', null, mv.text), bins = el('div', 'tr-bins');
      D.bins.forEach(function (b) {
        var lab = el('label', 'tr-bin'), inp = el('input');
        inp.type = 'radio'; inp.name = caseId + '-' + mv.id; inp.value = b.id; inp.setAttribute('data-move', mv.id);
        inp.addEventListener('change', function () { S.sorts[caseId][mv.id] = b.id; progress(); });
        lab.appendChild(inp); lab.appendChild(el('span', null, b.label)); bins.appendChild(lab);
      });
      fs.appendChild(lg); fs.appendChild(bins); li.appendChild(fs); list.appendChild(li);
    });
    form.appendChild(list);
    var act = el('div', 'tr-actions'), btn = el('button', 'btn btn-solid', S_.sort_submit), prog = el('p', 'tr-note', fmt(S_.sort_progress, { done: 0 })),
        err = el('p', 'tr-err', S_.sort_incomplete);
    btn.type = 'submit'; err.hidden = true; prog.id = 'prog-' + caseId;
    act.appendChild(btn); act.appendChild(prog); act.appendChild(err); form.appendChild(act); container.appendChild(form);
    function progress() { var n = Object.keys(S.sorts[caseId]).length; prog.textContent = fmt(S_.sort_progress, { done: n }); if (n === 8) err.hidden = true; }
    form.addEventListener('submit', function (e) {
      e.preventDefault();
      if (Object.keys(S.sorts[caseId]).length < 8) { err.hidden = false; err.focus && err.focus(); announce(S_.sort_incomplete); return; }
      form.querySelectorAll('input').forEach(function (i) { i.disabled = true; });
      btn.disabled = true;
      onSubmit();
    });
  }

  /* ---- enrol ------------------------------------------------------ */
  $('tr-enrol').addEventListener('submit', function (e) {
    e.preventDefault();
    var v = parseInt($('tr-slot').value, 10), err = $('tr-enrol-err');
    if (!(v >= 1 && v <= D.pilot.slots) || String(v) !== $('tr-slot').value.trim()) { err.hidden = false; return; }
    err.hidden = true;
    S.slot = v; S.arm = D.pilot.arms[String(v)];
    main.setAttribute('data-arm', S.arm);
    S.t0 = now(); $('tr-clock').hidden = false; tick();
    S.phases.push({ id: 'enrol', started: S.t0, ended: null });
    $('seal-lead').textContent = S.arm === 'A' ? S_.seal_lead_before : S_.seal_lead_after;
    $('tr-status').textContent = fmt(S_.enrol_arm, { slot: v });
    $('pre-title').textContent = D.cases.pre.title;
    renderCase($('pre-case'), D.cases.pre, { commitment: D.cases.pre.commitment, evidence: true, moves: true, caseId: 'pre', onSubmit: function () { next(); } });
    go('pre');
  });

  /* ---- the claim -------------------------------------------------- */
  var T = D.trained;
  $('claim-title').textContent = T.title;
  renderCase($('claim-case'), T, {});
  $('tr-predict-l').textContent = T.prediction_prompt + ' ' + S_.prediction_label.replace(/^Your expectation, /, '(') + ')';
  $('tr-publish').addEventListener('submit', function (e) {
    e.preventDefault();
    S.handle = $('tr-handle').value.trim().slice(0, 40);
    var p = $('tr-predict').value.trim();
    S.prediction = p === '' ? null : parseInt(p, 10);
    var box = $('tr-published'); box.innerHTML = '';
    var card = el('div', 'tr-published');
    card.appendChild(el('p', 'tr-claim', T.claim));
    card.appendChild(el('span', 'tr-stamp', S_.published + (S.handle ? ' · ' + S.handle : '')));
    box.appendChild(card); box.hidden = false;
    $('tr-publish').querySelectorAll('input,button').forEach(function (i) { i.disabled = true; });
    announce(S_.published);
    $('tr-publish-go').hidden = false; $('tr-publish-go').focus();
  });

  /* ---- the seal --------------------------------------------------- */
  $('seal-title').textContent = T.title;
  $('seal-falsifier').textContent = T.seal.falsifier;
  $('seal-cons-l').textContent = T.seal.consequence_prompt;
  $('seal-forb-l').textContent = T.seal.forbidden_prompt;
  T.seal.consequences.forEach(function (c) {
    var lab = el('label'), inp = el('input'); inp.type = 'radio'; inp.name = 'seal-cons'; inp.value = c.id;
    var txt = el('span'); txt.appendChild(el('b', null, c.id)); txt.appendChild(el('small', null, c.gloss));
    lab.appendChild(inp); lab.appendChild(txt); $('seal-cons').appendChild(lab);
  });
  T.seal.forbidden_candidates.forEach(function (c) {
    var lab = el('label'), inp = el('input'); inp.type = 'checkbox'; inp.name = 'seal-forb'; inp.value = c.id;
    lab.appendChild(inp); lab.appendChild(el('span', null, c.text)); $('seal-forb').appendChild(lab);
  });
  function hex(buf) { var a = new Uint8Array(buf), s = ''; for (var i = 0; i < a.length; i++) s += pad2(a[i].toString(16)); return s; }
  function pad2(x) { return x.length < 2 ? '0' + x : x; }
  function digest(text, cb) {
    if (window.crypto && crypto.subtle && window.TextEncoder) {
      crypto.subtle.digest('SHA-256', new TextEncoder().encode(text)).then(function (b) { cb(hex(b)); }, function () { cb('unavailable'); });
    } else cb('unavailable');
  }
  $('tr-seal').addEventListener('submit', function (e) {
    e.preventDefault();
    var cons = $('tr-seal').querySelector('input[name=seal-cons]:checked');
    var forb = Array.prototype.map.call($('tr-seal').querySelectorAll('input[name=seal-forb]:checked'), function (i) { return i.value; });
    var err = $('tr-seal-err');
    if (!cons || !forb.length) { err.hidden = false; announce(S_.seal_incomplete); return; }
    err.hidden = true;
    var at = new Date().toISOString();
    var seal = { falsifier: T.seal.falsifier, consequence: cons.value, forbidden: forb, at: at, slot: S.slot, arm: S.arm,
                 before_evidence: S.arm === 'A', instrument: D.instrument };
    $('tr-seal').querySelectorAll('input,button').forEach(function (i) { i.disabled = true; });
    digest(JSON.stringify(seal), function (h) {
      seal.hash = h; S.seal = seal;
      renderSeal($('seal-done'), true); $('seal-done').hidden = false;
      renderSeal($('sort-seal'), false);
      announce(fmt(S_.sealed, { hash: h.slice(0, 12), time: at }));
      $('tr-seal-go').hidden = false; $('tr-seal-go').focus();
    });
  });
  function renderSeal(box, withStamp) {
    box.innerHTML = '';
    box.appendChild(el('span', 'mono tr-lbl', S_.your_seal));
    box.appendChild(el('p', null, S_.case_falsifier + ' — ' + S.seal.falsifier));
    box.appendChild(el('p', null, S_.case_consequence + ' — ' + S.seal.consequence));
    var names = T.seal.forbidden_candidates.filter(function (c) { return S.seal.forbidden.indexOf(c.id) >= 0; }).map(function (c) { return c.text; });
    box.appendChild(el('p', null, S_.case_forbidden + ' — ' + names.join('; ')));
    box.appendChild(el('p', 'hash', fmt(S_.sealed, { hash: S.seal.hash, time: S.seal.at })));
    if (withStamp) box.appendChild(el('span', 'tr-stamp', S_.case_commitment.replace('BEFORE THE EVIDENCE', S.seal.before_evidence ? 'BEFORE THE EVIDENCE' : 'AFTER THE EVIDENCE')));
  }

  /* ---- the evidence ----------------------------------------------- */
  $('tr-publish-go').addEventListener('click', next);
  $('tr-seal-go').addEventListener('click', next);
  T.evidence.forEach(function (e) { $('evidence-list').appendChild(el('li', null, e)); });
  $('tr-evidence-go').addEventListener('click', next);

  /* ---- the sort --------------------------------------------------- */
  $('sort-title').textContent = T.title;
  renderCase($('sort-case'), T, { evidence: true, moves: true, caseId: 'trained', onSubmit: function () { renderDebrief(); next(); } });

  /* ---- the debrief ------------------------------------------------ */
  function binLabel(id) { for (var i = 0; i < D.bins.length; i++) if (D.bins[i].id === id) return D.bins[i].label; return id; }
  function renderDebrief() {
    var key = $('debrief-key'); key.innerHTML = '';
    var n = 0, mirrors = [];
    T.moves.forEach(function (mv) {
      var mine = S.sorts.trained[mv.id], tpl = D.templates[mv.template], ok = mine === mv.key;
      if (ok) n++;
      var li = el('li', ok ? 'ok' : 'no');
      li.appendChild(el('p', null, mv.text));
      var v = el('p', 'verdict');
      var you = el('span'); you.appendChild(el('span', 'mono', S_.debrief_you + ' ')); you.appendChild(el('b', null, binLabel(mine)));
      var k = el('span'); k.appendChild(el('span', 'mono', S_.debrief_key + ' ')); k.appendChild(el('b', null, binLabel(mv.key)));
      v.appendChild(you); v.appendChild(k); v.appendChild(el('span', 'mono', tpl.name));
      li.appendChild(v);
      li.appendChild(el('p', 'rule', tpl.rule));
      li.appendChild(el('p', 'src', S_.debrief_source + ' ' + tpl.sources.join(' · ')));
      if (tpl.mirror && S.seal && S.seal.forbidden.indexOf(tpl.mirror) >= 0) {
        if (mv.key === 'rescue' && mine !== 'rescue') {
          li.appendChild(el('p', 'mirror', fmt(S_.debrief_mirror, { bin: binLabel(mine).toLowerCase() })));
          mirrors.push(mv.id);
        } else if (mv.key !== 'rescue') {
          li.appendChild(el('p', 'mirror', S_.debrief_overreach));
        }
      }
      key.appendChild(li);
    });
    $('debrief-score').textContent = fmt(S_.debrief_score, { n: n });
    $('debrief-mirror').textContent = mirrors.length ? '' : S_.debrief_mirror_none;
    $('debrief-govern').textContent = D.governing_rule;
    var qs = $('debrief-qs'); qs.innerHTML = '';
    D.two_questions.forEach(function (q) { qs.appendChild(el('li', null, q)); });
  }
  $('tr-debrief-go').addEventListener('click', next);

  /* ---- update + recall -------------------------------------------- */
  $('update-title').textContent = T.title;
  $('tr-update').addEventListener('submit', function (e) {
    e.preventDefault();
    var u = $('tr-updated').value.trim(), r = $('tr-recall').value.trim(), err = $('tr-update-err');
    if (!u || !r) { err.hidden = false; announce(S_.update_incomplete); return; }
    err.hidden = true; S.updated = u; S.recall = r;
    $('tr-update').querySelectorAll('textarea,button').forEach(function (i) { i.disabled = true; });
    $('cold-title').textContent = D.cases.cold.title;
    renderCase($('cold-case'), D.cases.cold, { commitment: D.cases.cold.commitment, evidence: true, moves: true, caseId: 'cold', onSubmit: function () { next(); } });
    next();
  });

  /* ---- reactions + receipt ---------------------------------------- */
  function scale(container, name) {
    for (var i = 1; i <= 5; i++) {
      var lab = el('label', 'tr-bin'), inp = el('input'); inp.type = 'radio'; inp.name = name; inp.value = String(i);
      lab.appendChild(inp); lab.appendChild(el('span', null, String(i))); container.appendChild(lab);
    }
  }
  scale($('tr-conf'), 'tr-conf'); scale($('tr-help'), 'tr-help');
  $('tr-react').addEventListener('submit', function (e) {
    e.preventDefault();
    var c = $('tr-react').querySelector('input[name=tr-conf]:checked'), h = $('tr-react').querySelector('input[name=tr-help]:checked');
    S.confidence = c ? parseInt(c.value, 10) : null; S.helped = h ? parseInt(h.value, 10) : null; S.comment = $('tr-comment').value.trim();
    $('tr-react').querySelectorAll('input,textarea,button').forEach(function (i) { i.disabled = true; });
    var t = now(); if (S.phases.length) S.phases[S.phases.length - 1].ended = t;
    var receipt = {
      instrument: D.id, version: D.version, experiment: D.experiment, instrument_hash: D.instrument,
      slot: S.slot, arm: S.arm, started: new Date(S.t0).toISOString(), finished: new Date(t).toISOString(),
      total_seconds: Math.round((t - S.t0) / 1000),
      phases: S.phases.map(function (p) { return { id: p.id, seconds: p.ended ? Math.round((p.ended - p.started) / 1000) : null }; }),
      pre: S.sorts.pre, handle: S.handle, prediction: S.prediction, seal: S.seal, trained: S.sorts.trained,
      updated_claim: S.updated, rule_recall: S.recall, cold: S.sorts.cold,
      confidence: S.confidence, helped: S.helped, comment: S.comment
    };
    finished = true;
    var ta = $('tr-receipt'); ta.value = JSON.stringify(receipt, null, 1);
    $('tr-receipt-wrap').hidden = false; ta.focus(); ta.select();
    announce(S_.receipt_lead);
  });
  $('tr-copy').addEventListener('click', function () {
    var ta = $('tr-receipt'); ta.focus(); ta.select();
    function done() { $('tr-copied').hidden = false; announce(S_.copied); }
    if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(ta.value).then(done, function () { try { document.execCommand('copy'); } catch (e) {} done(); });
    else { try { document.execCommand('copy'); } catch (e) {} done(); }
  });

  /* ---- leaving loses the record; nothing is stored ------------------ */
  var finished = false;
  window.addEventListener('beforeunload', function (e) {
    if (S.t0 === null || finished) return;
    e.preventDefault(); e.returnValue = S_.leave_warning; return S_.leave_warning;
  });

  /* ---- reduced motion is honoured by CSS; nothing here animates ----- */
  var reduced = matchMedia('(prefers-reduced-motion: reduce)');
  if (reduced.matches) root.classList.add('tr-reduced');
})();
