#!/usr/bin/env python3
"""Generate docs/RESEARCH_INDEX.md — a compact factual index for technical reviewers.

Derived entirely from the registries (claims.yaml, distribution/outcomes.yaml,
distribution/experiments.yaml, films/*/manifest.yaml); --check fails on
drift. Nothing here is written by hand: a reviewer reads the same statuses,
boundaries and reproduction commands the site renders. No adoption, traction
or independence is asserted beyond what the outcomes ledger records — and
that ledger's zeros are printed as zeros.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import outcomes as outcomes_ledger  # noqa: E402

OUT = ROOT / "docs" / "RESEARCH_INDEX.md"

# Claim → the command that reproduces it, if one is registered.
REPRO = {
    "CC-001": "python3 scripts/reproduce_cc001.py",
    "CC-004": "python3 scripts/reproduce_cc001.py",
    "MC-001": "python3 scripts/verify_census.py --counts",
    "MC-002": "python3 scripts/reanalyze_bells_subset.py",
    "MC-003": "python3 scripts/identification.py",
    "MC-004": "python3 scripts/reanalyze_msbench.py",
    "AF-001": "python3 scripts/mixture_bounds.py",
}


def one_line(text: str, limit: int = 220) -> str:
    text = " ".join(str(text).split())
    return text if len(text) <= limit else text[:limit - 1].rstrip() + "…"


def render() -> str:
    claims = yaml.safe_load((ROOT / "claims.yaml").read_text())
    ledger = outcomes_ledger.load()
    experiments = yaml.safe_load((ROOT / "distribution" / "experiments.yaml").read_text())
    films = {}
    for m in sorted(ROOT.glob("films/*/manifest.yaml")):
        d = yaml.safe_load(m.read_text())
        for c in d.get("evidence_commits", []):
            films.setdefault(c["claim"], []).append(d["id"])
    q = ledger["qualified"]
    L = ["# Research index", "",
         "GENERATED by scripts/generate_research_index.py from claims.yaml, distribution/outcomes.yaml, distribution/experiments.yaml and the film manifests. Do not edit by hand.", "",
         f"Registry v{claims['version']} · last owner review {claims['last_owner_review']} · one question: *{experiments['question']}*", "",
         "## Independent outcomes (someone who is not the author did work)", "",
         "| bucket | count |", "|---|---|"]
    for bucket in outcomes_ledger.QUALIFIED_BUCKETS:
        L.append(f"| {bucket.replace('_', ' ')} | {len(q[bucket])} |")
    L += [f"| technical interactions (diagnostic, not an outcome) | {ledger['diagnostics']['technical_interactions']} |", "",
          "Zero is the recorded value where it is zero. The stop rule and the procedure for recording an outcome are in `distribution/EXTERNAL_EVENTS.md`.", "",
          "## Claims", "",
          "| id | question / result | status · maturity | reproduce | boundary (first non-claim) | films |", "|---|---|---|---|---|---|"]
    for c in claims["claims"]:
        d = c["dimensions"]
        nc = c.get("non_claims") or ["—"]
        L.append(f"| {c['id']} | {one_line(c['proposition'])} | {d['evidential_status']} · {d['maturity']} | "
                 f"{('`' + REPRO[c['id']] + '`') if c['id'] in REPRO else '—'} | {one_line(nc[0], 160)} | "
                 f"{', '.join(films.get(c['id'], [])) or '—'} |")
    L += ["", "## Experiments an outsider can run", "", "| id | minutes | command | expected final line |", "|---|---|---|---|"]
    for e in experiments["experiments"]:
        L.append(f"| {e['id']} | {e['minutes']} | `{e['command']}` | `{e['expected_final_line']}` |")
    L += ["", "## Communication artifacts", "",
          "Six deterministic films under `films/` (manifests bind every number to the registries; see `films/README.md`); launch units in `distribution/launch-units.yaml` (status PREPARED); the experiment surface at `/try/`.", ""]
    return "\n".join(L)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"DRIFT: {OUT.relative_to(ROOT)} does not match the registries. Run: python3 scripts/generate_research_index.py")
            return 1
        print("ok    research index matches the registries")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
