#!/usr/bin/env python3
"""Generate sitemap.xml with lastmod derived from git history.

A bulk-stamped lastmod is an unverifiable claim, and search engines are
documented to ignore lastmod unless it is consistently accurate — so each
URL's lastmod is the date of the last commit that touched its page file.
A file with uncommitted modifications gets today's date (the date the
pending commit will carry).

`--check` fails when the committed sitemap's URL set or ordering drifts
from the discovered pages; lastmod values are compared only when full git
history is available (a shallow CI clone cannot know per-file dates, and
pretending it could would be exactly the kind of claim this site exists
to refuse).
"""

import datetime
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = "https://cubits11.github.io"


def discover_pages() -> list:
    pages = [ROOT / "index.html"]
    for p in sorted(ROOT.rglob("index.html")):
        rel = p.relative_to(ROOT)
        if rel.parts[0] in (".git", "docs", "scripts") or rel == pathlib.Path("index.html"):
            continue
        pages.append(p)
    return pages


def url_for(page: pathlib.Path) -> str:
    rel = page.relative_to(ROOT)
    if rel == pathlib.Path("index.html"):
        return f"{SITE}/"
    return f"{SITE}/{rel.parent.as_posix()}/"


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                          text=True).stdout.strip()


def is_shallow() -> bool:
    return git("rev-parse", "--is-shallow-repository") == "true"


def lastmod_for(page: pathlib.Path) -> str:
    rel = page.relative_to(ROOT).as_posix()
    if git("status", "--porcelain", "--", rel):
        return datetime.date.today().isoformat()
    date = git("log", "-1", "--format=%cs", "--", rel)
    return date or datetime.date.today().isoformat()


def render() -> str:
    entries = []
    for page in discover_pages():
        entries.append(f"  <url><loc>{url_for(page)}</loc>"
                       f"<lastmod>{lastmod_for(page)}</lastmod></url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!-- GENERATED by scripts/generate_sitemap.py — lastmod is each '
            "page file's last commit date, not a bulk stamp. -->\n"
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(entries) + "\n</urlset>\n")


def main() -> int:
    out = render()
    target = ROOT / "sitemap.xml"
    if "--check" in sys.argv:
        current = target.read_text() if target.exists() else ""
        def urls(text: str) -> list:
            """The URL identities alone.

            Reading whole ``<loc>`` lines would fold each entry's lastmod
            into the comparison, so a date-only change would be reported as
            URL drift the check never established. A verifier that names the
            wrong cause is the failure mode this site exists to refuse.
            """
            return re.findall(r"<loc>([^<]+)</loc>", text)
        if urls(current) != urls(out):
            print("DRIFT: sitemap.xml URL set does not match discovered pages.")
            print("Run: python scripts/generate_sitemap.py")
            return 1
        if not is_shallow() and current != out:
            print("DRIFT: sitemap.xml lastmod values do not match git history.")
            print("Run: python scripts/generate_sitemap.py")
            return 1
        note = " (URL set only — shallow clone)" if is_shallow() else ""
        print(f"ok    sitemap.xml matches discovered pages{note}")
        return 0
    target.write_text(out)
    print(f"wrote sitemap.xml ({out.count('<loc>')} URLs, lastmod from git)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
