#!/usr/bin/env python3
"""Generate watch pages from film manifests, actual render receipts and deployment history.

No upload date is inferred from a render date. Publication history records
successful GitHub Pages deployments containing each existing primary video.
No model performance claim is introduced by this renderer.
"""
from __future__ import annotations

import copy
import datetime as dt
import hashlib
import json
from pathlib import Path
import sys
import yaml

from generate_claims_pages import SITE, SITE_HEAD, OG_IMAGE, OG_ALT, breadcrumbs, head, footer, esc, squash

ROOT = Path(__file__).resolve().parent.parent
BANNER = '<!doctype html>\n<!-- GENERATED by scripts/generate_film_pages.py; do not hand-edit. -->\n'
STYLE = '''<style>
.container{width:min(1080px,100% - 2*clamp(1.25rem,5vw,3rem))}
header.page{padding:6.8rem 0 1.2rem}h1.q{max-width:24ch;margin-bottom:.65rem}
.film-note{max-width:65ch;color:var(--muted);margin:.45rem 0 1rem}
.watch{width:100%;height:auto;display:block;max-height:72vh;aspect-ratio:var(--ratio);background:#0B0F0A;border:1px solid var(--line-strong)}
.watch:focus-visible{outline:3px solid var(--evidence);outline-offset:4px}
.film-meta{display:flex;flex-wrap:wrap;gap:.65rem 1.4rem;margin:.9rem 0 1.4rem;color:var(--muted);font-family:var(--mono);font-size:.72rem}
.film-body{max-width:760px}.film-body p,.film-body li{overflow-wrap:anywhere}
.film-body h2{font-family:var(--serif);font-size:1.65rem;font-weight:500}
.film-body ul{padding-left:1.3rem}.film-body li{margin:.6rem 0}
.film-body details{border-top:1px solid var(--line);margin-top:1.5rem;padding-top:1rem}
.film-body summary{cursor:pointer;color:var(--ink);font-family:var(--mono);font-size:.8rem}
.film-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:2rem 1.4rem;list-style:none;padding:0;margin:1rem 0 3rem}
.film-card{display:block;text-decoration:none;border:1px solid var(--line);background:var(--surface);height:100%;transition:border-color .15s}
.film-card:hover,.film-card:focus-visible{border-color:var(--evidence)}
.film-card img{display:block;width:100%;aspect-ratio:16/9;object-fit:contain;background:#0B0F0A}
.film-card div{padding:1rem 1.1rem}.film-card h2{font-family:var(--serif);font-size:1.45rem;font-weight:500;line-height:1.2;margin:0 0 .65rem;color:var(--ink)}
.film-card p{font-size:.84rem;color:var(--muted);margin:0}
@media(max-width:600px){.film-grid{grid-template-columns:1fr;gap:1.1rem}header.page{padding-top:6.2rem}.watch{max-height:65vh}.film-meta{gap:.5rem 1rem}}
</style>'''


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def route(slug: str) -> str:
    return f'/films/{slug}/'


def public_path(rel: str) -> str:
    return f'{SITE}/{rel}'


def validate_record(manifest: dict, receipt: dict, publication: dict) -> None:
    slug = manifest['id']
    fmt = manifest.get('render', {}).get('primary', 'master')
    expected = f'films/{slug}/renders/{slug}__{fmt}.mp4'
    if receipt['film'] != slug or receipt['format'] != fmt:
        raise ValueError(f'{slug}: wrong render receipt')
    if publication['film'] != slug or publication['video_path'] != expected:
        raise ValueError(f'{slug}: publication record names a different video')
    if publication['primary_format'] != fmt or publication['status'] != 'success':
        raise ValueError(f'{slug}: no successful primary-video publication')
    if publication['environment_url'] != SITE + '/':
        raise ValueError(f'{slug}: publication belongs to another site')
    date = dt.datetime.fromisoformat(publication['first_site_publication'].replace('Z', '+00:00'))
    if date.tzinfo is None:
        raise ValueError(f'{slug}: publication timestamp has no timezone')
    expected_source = f"https://api.github.com/repos/Cubits11/cubits11.github.io/deployments/{publication['deployment_id']}/statuses"
    if publication['source_url'] != expected_source:
        raise ValueError(f'{slug}: deployment source differs')
    if not receipt['determinism']['identical'] or receipt['text_overflows']:
        raise ValueError(f'{slug}: render did not pass determinism/overflow checks')
    if abs(float(receipt['duration_s']) - float(manifest['duration_s'])) > 1 / receipt['fps']:
        raise ValueError(f'{slug}: duration differs from the declared film')
    if receipt['outputs']['master'] != f'renders/{slug}__{fmt}.mp4':
        raise ValueError(f'{slug}: render output points at another file')


def load_films() -> list[dict]:
    history = json.loads((ROOT / 'films/publication-history.json').read_text())
    pubs = {p['film']: p for p in history['films']}
    if len(pubs) != len(history['films']):
        raise ValueError('duplicate film publication record')
    films = []
    for path in sorted((ROOT / 'films').glob('*/manifest.yaml')):
        m = yaml.safe_load(path.read_text())
        slug = path.parent.name
        if slug != m['id']:
            raise ValueError(f'{slug}: mismatched manifest id')
        fmt = m.get('render', {}).get('primary', 'master')
        receipt_path = path.parent / f'renders/{slug}__{fmt}.receipt.json'
        r = json.loads(receipt_path.read_text())
        publication = pubs[slug]
        validate_record(m, r, publication)
        for rel, digest in r['inputs'].items():
            source = path.parent / rel if rel == 'film.html' else ROOT / rel
            if sha(source) != digest:
                raise ValueError(f'{slug}: render input is stale: {rel}')
        video = path.parent / r['outputs']['master']
        if sha(video) != r['outputs']['master_sha256']:
            raise ValueError(f'{slug}: video bytes differ from render receipt')
        poster = path.parent / r['outputs']['poster']
        if not poster.is_file():
            raise ValueError(f'{slug}: poster missing')
        films.append({'manifest': m, 'receipt': r, 'publication': publication,
                      'video': video.relative_to(ROOT).as_posix(),
                      'poster': poster.relative_to(ROOT).as_posix(),
                      'receipt_path': receipt_path.relative_to(ROOT).as_posix()})
    if set(pubs) != {f['manifest']['id'] for f in films}:
        raise ValueError('publication inventory differs from film manifests')
    return films


def description(film: dict) -> str:
    m = film['manifest']
    return (f"Watch {m['title']}, a {m['duration_s']:g}-second silent film. "
            'Read its visual argument, stated scope, evidence, falsifier and limits.')


def video_node(film: dict) -> dict:
    m, r, pub = film['manifest'], film['receipt'], film['publication']
    return {'@context': 'https://schema.org', '@type': 'VideoObject',
            '@id': SITE + route(m['id']) + '#video', 'name': m['title'],
            'description': description(film), 'url': SITE + route(m['id']),
            'thumbnailUrl': [public_path(film['poster'])],
            'contentUrl': public_path(film['video']),
            'uploadDate': pub['first_site_publication'],
            'duration': f"PT{r['outputs']['master_duration_probe_s']:g}S",
            'width': r['width'], 'height': r['height'], 'inLanguage': 'en',
            'isAccessibleForFree': True,
            'creator': {'@type': 'Person', '@id': SITE + '/#person', 'name': 'Pranav Bhave'},
            'mainEntityOfPage': {'@type': 'WebPage', '@id': SITE + route(m['id'])}}


def render_film(film: dict) -> str:
    m, r, pub = film['manifest'], film['receipt'], film['publication']
    slug = m['id']
    heading = head(m['title'] + ' | Film', description(film), route(slug), 'video.other',
                   [video_node(film), breadcrumbs([('The record', SITE + '/'), ('Films', SITE + '/films/'), (m['title'], None)])])
    heading = heading.replace(OG_IMAGE, public_path(film['poster'])).replace(esc(OG_ALT), esc('Still from ' + m['title']))
    heading = heading.replace('</head>', STYLE + '</head>')
    limits = ''.join(f'<li>{esc(n)}</li>' for n in m['non_claims'])
    evidence_ids = sorted({e['fact'].split('.')[0] for e in m.get('evidence', [])})
    evidence_links = []
    for cid in evidence_ids:
        target = ROOT / 'claims' / cid.lower() / 'index.html'
        if target.is_file():
            evidence_links.append(f'<a class="u" href="/claims/{cid.lower()}/">{esc(cid)}</a>')
    evidence = ' · '.join(evidence_links) or '<a class="u" href="/corrections/">Correction policy</a>'
    return BANNER + heading + SITE_HEAD + f'''
<header class="page"><div class="container">
<p class="eyebrow mono">Film · {m['duration_s']:g} seconds · silent</p>
<h1 class="q">{esc(m['title'])}</h1>
<p class="film-note">{esc(m['thesis'])}</p>
</div></header>
<main id="main" class="container">
<video class="watch" id="film" controls playsinline preload="metadata" poster="/{film['poster']}" width="{r['width']}" height="{r['height']}" style="--ratio:{r['width']}/{r['height']}" aria-label="{esc(m['title'])}" aria-describedby="text-alternative">
<source src="/{film['video']}" type="video/mp4">
Your browser cannot play this video. <a href="/{film['video']}">Download the film</a> or read the text below.
</video>
<div class="film-meta"><a class="u" href="#text-alternative">Read the argument</a><a class="u" href="/{film['video']}" download>Download MP4</a><span>First published here {pub['first_site_publication'][:10]}</span></div>
<div class="film-body">
<section class="gsec" id="text-alternative" aria-labelledby="argument-title"><h2 id="argument-title">The argument in text</h2>
<p>{esc(m['claim'])}</p><p>{esc(m['scope'])}</p></section>
<section class="gsec"><h2>What this does not establish</h2><ul>{limits}</ul></section>
<section class="gsec"><h2>What would require a correction</h2><p>{esc(m['falsifier'])}</p>
<p>Read the supporting record: {evidence}.</p></section>
<details><summary>Sources and render record</summary>
<p><a class="u" href="/films/{slug}/manifest.yaml">Film manifest</a> · <a class="u" href="/{film['receipt_path']}">Render receipt</a> · <a class="u" href="{pub['source_url']}">First site deployment record</a></p>
<p>Current render: {esc(r['rendered_on'])}. The receipt records the rendered inputs and output hash. It checks provenance, not scientific validity.</p></details>
</div></main>
''' + footer([('/films/', 'All films'), ('/claims/', 'Claim registry'), ('/missing-column/', 'The Missing Column'), ('/corrections/', 'Corrections')])


def render_index(films: list[dict]) -> str:
    title = 'Films — safety scores, hidden overlap and checkable claims'
    desc = f"{len(films)} short, silent films about guardrail composition and evidence. Watch each argument with its source claims, scope, falsifier and limits alongside it."
    node = {'@context': 'https://schema.org', '@type': 'CollectionPage', 'name': title,
            'description': desc, 'url': SITE + '/films/', 'mainEntity': {'@type': 'ItemList',
                'numberOfItems': len(films), 'itemListElement': [
                    {'@type': 'ListItem', 'position': i, 'name': f['manifest']['title'], 'url': SITE + route(f['manifest']['id'])}
                    for i, f in enumerate(films, 1)]}}
    cards = ''.join(f'''<li><a class="film-card" href="{route(f['manifest']['id'])}">
<img src="/{f['poster']}" width="{f['receipt']['width']}" height="{f['receipt']['height']}" loading="lazy" alt="Still from {esc(f['manifest']['title'])}">
<div><h2>{esc(f['manifest']['title'])}</h2><p>{f['manifest']['duration_s']:g} seconds · silent · argument and sources in text</p></div></a></li>''' for f in films)
    return (BANNER + head(title, desc, '/films/', 'website', [node]).replace('</head>', STYLE + '</head>') + SITE_HEAD + f'''
<header class="page"><div class="container"><p class="eyebrow mono">Watch · inspect · challenge</p>
<h1 class="q">What the scores leave out</h1><p class="standfirst">{len(films)} short visual arguments about guardrail composition, uncertainty and evidence. Every film has a text alternative and a route back to its claims.</p></div></header>
<main class="container" id="main"><ul class="film-grid">{cards}</ul></main>
''' + footer([('/claims/', 'Claim registry'), ('/missing-column/', 'The Missing Column'), ('/corrections/', 'Corrections')]))


def build() -> dict[Path, str]:
    films = load_films()
    return {ROOT / 'films/index.html': render_index(films),
            **{ROOT / 'films' / f['manifest']['id'] / 'index.html': render_film(f) for f in films}}


def self_test() -> int:
    f = load_films()[0]
    m, r, pub = f['manifest'], f['receipt'], f['publication']
    for key, value in [('status', 'failure'), ('video_path', 'wrong.mp4'), ('first_site_publication', '2026-09-15'), ('source_url', 'https://example.com/')]:
        broken = copy.deepcopy(pub); broken[key] = value
        try:
            validate_record(m, r, broken)
        except ValueError:
            pass
        else:
            raise AssertionError(f'accepted invalid publication field {key}')
    changed = copy.deepcopy(f); changed['receipt']['rendered_on'] = '2099-01-01'
    assert video_node(changed)['uploadDate'] == pub['first_site_publication']
    broken = copy.deepcopy(r); broken['determinism']['identical'] = False
    try:
        validate_record(m, broken, pub)
    except ValueError:
        pass
    else:
        raise AssertionError('accepted nondeterministic render')
    for film in load_films():
        node = video_node(film)
        assert set(['name', 'description', 'thumbnailUrl', 'uploadDate', 'contentUrl', 'duration']) <= node.keys()
        assert 'license' not in node and 'interactionStatistic' not in node
    print('ok    film metadata: failed deployments, wrong paths, undated publication and failed renders refuse; render date cannot become upload date')
    return 0


def main() -> int:
    try:
        if '--test' in sys.argv:
            return self_test()
        output = build()
        stale = []
        for path, text in output.items():
            if '--check' in sys.argv:
                if not path.exists() or path.read_text() != text:
                    stale.append(path.relative_to(ROOT).as_posix())
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text)
        if stale:
            raise ValueError('watch page drift: ' + ', '.join(stale))
        print(f"ok    {len(output)} film pages {'verified' if '--check' in sys.argv else 'generated'}")
        return 0
    except (ValueError, KeyError, OSError) as exc:
        print('FAIL ', exc)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
